name: WhatsApp
description: WhatsApp UI Clone
version: 1.0.0+1
author : Vaibhav Shrotriya
homepage : vaibhavshrotriya.ml
repository : https://github.com/vishu1299/WhatsAppClone

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  camera : ^0.5.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Ouicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
